name: docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20.4'
     
      - name: Check out code
        uses: actions/checkout@v2

      - name: Test application
        run: go test ./...
     
      - name: Build application
        run: |
          CGO_ENABLED=0
          GOOS=linux
          GOARCH=amd64
          go build -o endpoint -o build/endpoint main.go
     
      - name: Build Docker image
        run: |
          docker build -t endpoint:1.0.0 .
     
      - name: Publish Docker image
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
     
      - name: Push Docker image
        run: |
          docker push endpoint:1.0.0
